config/routes.rb
Rails.application.routes.draw do
  # 認証ページURLパスを変更
  devise_for :users, path_names: {
  sign_in: "login",
  sign_out: "logout",
  sign_up: "register"
  }

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: "boards#index"
  resources :boards do
    resources :cards do
      resources :comments, only: [ :new, :create ]
    end
  end

  resource :profiles, only: [ :show, :edit, :update ]

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/profile.rb
# == Schema Information
#
# Table name: profiles
#
#  id         :bigint           not null, primary key
#  nickname   :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_profiles_on_user_id  (user_id)
#
class Profile < ApplicationRecord
  belongs_to :user
  has_one_attached :avatar
  validates :nickname, presence: true

  def self.ransackable_attributes(auth_object = nil)
    %w[nickname]
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  before_action :authenticate_user!
  def show
    @profile = current_user.profile
  end

  def edit
    @profile = current_user.prepare_profile
  end

  def update
    @profile = current_user.prepare_profile
    @profile.assign_attributes(profile_params)
    if @profile.save
      redirect_to profile_path, notice: 'プロフィール更新！'
    else
      flash.now[:error] = '更新できませんでした'
      render :edit
    end
  end

  private
  def profile_params
    params.require(:profile).permit(
      :nickname,
      :avatar
    )
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!
  def show
    @profile = current_user.profile
  end

  def edit
    @profile = current_user.prepare_profile
  end

  def update
    @profile = current_user.prepare_profile
    @profile.assign_attributes(profile_params)
    if @profile.save
      redirect_to profiles_path, notice: "プロフィール更新！"
    else
      flash.now[:error] = "更新できませんでした"
      render :edit
    end
  end

  private
  def profile_params
    params.require(:profile).permit(
      :nickname,
      :avatar
    )
  end
end

app/views/profiles/edit.html.haml
.inner.inner-form
  %ul
    - @profile.errors.full_messages.each do |message|
      %li= message

  = form_with(model: @profile, url: profiles_path(@profile), method: :put, local: true, html: { id: 'profile-form' }) do |f|
    .form-field
      .form-avatar
        - if @profile.avatar.attached?
          = image_tag @profile.avatar, id: 'avatar-preview'
          %p.file-name#avatar-filename= @profile.avatar.filename.to_s
        - else
          = image_tag 'default-avatar.png', id: 'avatar-preview'
          %p.file-name#avatar-filename 選択されていません

      = f.label :avatar, class: 'form-label'
      = f.file_field :avatar, class: 'form-text', id: 'avatar-input'

    .form-field
      = f.label :nickname, class: 'form-label'
      = f.text_field :nickname, class: 'form-text'

    .form-actions
      = f.submit '保存', class: 'btn-primary'

app/views/profiles/show.html.haml
.inner
  %h2 プロフィール情報
  .profile
    .profile-image
      = image_tag current_user.avatar_image
    .profile-name
      #{current_user.display_name}
    .profile-button
      = link_to t('activerecord.attributes.profile.edit_profile'), edit_profiles_path
  .profile-link
    = link_to t('activerecord.attributes.profile.edit_account'), edit_user_registration_path