config/routes.rb
Rails.application.routes.draw do
  # 認証ページURLパスを変更
  devise_for :users, path_names: {
  sign_in: "login",
  sign_out: "logout",
  sign_up: "register"
  }

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: "boards#index"
  resources :boards do
    resources :cards do
      resources :comments, only: [ :new, :create ]
    end
  end

  resource :profiles, only: [ :show, :edit, :update ]

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :bigint           not null, primary key
#  content    :text             not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  card_id    :bigint           not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_comments_on_card_id  (card_id)
#  index_comments_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (card_id => cards.id)
#  fk_rails_...  (user_id => users.id)
#
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :card
  validates :content, presence: true

  def self.ransackable_attributes(_auth_object = nil)
    %w[id content created_at updated_at]
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @card = Card.find(params[:card_id])
    @board = @card.board
    @comment = @card.comments.build
  end

  def create
    @card = Card.find(params[:card_id])
    @board = @card.board
    @comment = @card.comments.build(comment_params)
    @comment.user = current_user

    if @comment.save
      redirect_to board_card_path(@board, @card), notice: "コメントを追加しました"
    else
      flash.now[:error] = "更新できませんでした"
      render :new
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/edit.html.haml
%h1 Comments#edit
%p Find me in app/views/comments/edit.html.haml

app/views/comments/index.html.haml
%h1 Comments#index
%p Find me in app/views/comments/index.html.haml

app/views/comments/new.html.haml
.inner.inner-form
  %h2.comment-title 新しいコメントを作成
  %ul
    - @comment.errors.full_messages.each do |message|
      %li= message

  = form_with(model: @comment, url: board_card_comments_path(@board, @card), local: true) do |f|
    .form-field
      = f.label  :content,class: 'form-label'
      = f.text_area :content,class: 'form-text text-area'
    .form-actions
      = f.submit '保存', class: 'btn-primary'

app/views/comments/show.html.haml
%h1 Comments#show
%p Find me in app/views/comments/show.html.haml