config/routes.rb
Rails.application.routes.draw do
  # 認証ページURLパスを変更
  devise_for :users, path_names: {
  sign_in: "login",
  sign_out: "logout",
  sign_up: "register"
  }

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: "boards#index"
  resources :boards do
    resources :cards do
      resources :comments, only: [ :new, :create ]
    end
  end

  resource :profiles, only: [ :show, :edit, :update ]

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/board.rb
# == Schema Information
#
# Table name: boards
#
#  id          :bigint           not null, primary key
#  description :text             not null
#  title       :string           not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :bigint           not null
#
# Indexes
#
#  index_boards_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Board < ApplicationRecord
  validates :title, presence: true
  validates :title, length: { minimum: 2, maximum: 100 }
  validates :title, format: { with: /\A(?!\@)/ }
  validates :description, presence: true
  validates :description, length: { minimum: 5 }

  belongs_to :user
  has_many :cards, dependent: :destroy

  def self.ransackable_attributes(auth_object = nil)
    %w[id title description created_at updated_at]
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: [ :edit, :update ]
  before_action :authenticate_user!, only: [ :new, :create, :edit, :update, :destroy ]

def index
  @q = Board.ransack(params[:q])
  @q.sorts = "created_at desc" if @q.sorts.blank?
  @boards = @q.result.includes(:user, :cards).page(params[:page])
end


  def show
    @board = Board.find(params[:id])
    @q = @board.cards.includes(user: :profile).ransack(params[:q])
    @cards = @q.result.page(params[:page])
  end

  def new
    @board = current_user.boards.build
  end

  def create
    @board = current_user.boards.build(board_params)
    if @board.save
      redirect_to board_path(@board), notice: "\u4FDD\u5B58\u3067\u304D\u307E\u3057\u305F"
    else
      flash.now[:error] = "\u4FDD\u5B58\u306B\u5931\u6557\u3057\u307E\u3057\u305F"
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @board.update(board_params)
      redirect_to board_path(@board), notice: "\u66F4\u65B0\u3067\u304D\u307E\u3057\u305F"
    else
      flash.now[:error] = "\u66F4\u65B0\u306B\u5931\u6557\u3057\u307E\u3057\u305F"
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    board = current_user.boards.find(params[:id])
    board.destroy!
    redirect_to boards_path, status: :see_other, notice: "\u524A\u9664\u306B\u6210\u529F\u3057\u307E\u3057\u305F"
  end

  private

  def set_board
    @board = Board.find(params[:id])
  end

  def board_params
    params.require(:board).permit(:title, :description)
  end
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/views/boards/_form.html.haml
.form
	%ul
		- board.errors.full_messages.each do |message|
			%li= message
	= form_with(model: board, local: true) do |f|
		.form-field
			= f.label :title, class: 'form-label'
			= f.text_field :title,class: 'form-text'
		.form-field
			= f.label :description,class: 'form-label'
			= f.text_area :description,class: 'form-text text-area'
		.form-actions
			= f.submit '保存', class: 'btn-primary'

app/views/boards/edit.html.haml
.inner.inner-form
  %h2 ボードの編集
  = render 'form', board: @board

app/views/boards/index.html.haml
.inner
  %h2 ボード一覧
  = search_form_for @q, url: boards_path, method: :get, html: { class: 'search-form is-board' } do |f|
    .search-item
      .search-sorts
        %p= sort_link(@q, :id, "ボード番号", class: 'filter-button')
    .search-item
      = f.search_field :title_cont, placeholder: "ボード名を入力", class: 'filter-box'
      .search-buttons
        = f.submit "検索", class: 'filter-button'
        = link_to "リセット", boards_path, class: 'filter-button'
  .boards
    - @boards.each do |board|
      = link_to board_path(board), class: 'board' do
        .board-top
          .board-content
            .board-title
              %span= "B%03d:" % board.id
              = board.title
            .board-description= board.description
          .board-author
            %p 管理者
            .board-image= image_tag board.user.avatar_image
            .board-name= board.user.display_name
        .board-cards
          - unless board.cards.empty?
            .board-cards-title カード一覧
          %ul.board-cards-list
            - board.cards.each do |card|
              %li.board-card
                %span= "C%03d:" % card.id
                = card.title
  .pagination-wrapper
    = paginate @boards, params: request.query_parameters, theme: nil
  - if user_signed_in?
    = link_to new_board_path, class: 'board-create' do
      .board-create-content ＋ 新しいボードを作成

app/views/boards/new.html.haml
.inner.inner-form
  %h2 新しいボードを作成
  = render 'form', board: @board

app/views/boards/show.html.haml
.inner
  .board-back= link_to '＜ ボード一覧に戻る', root_path()
  .card-top
    .card-title
      %h2
        %span= "B%03d:" % @board.id
        = @board.title
      %h3= @board.description
    - if user_signed_in? && current_user.boards.exists?(id: @board.id)
      .card-actions
        .card-icon
          = image_tag 'actions.svg', alt: 'Actions Icon'
          .dropdown-content.mini
            = link_to '編集する', edit_board_path(@board)
            = link_to '削除する', board_path(@board), data: { turbo_method: 'delete', turbo_confirm: '本当に削除してもよろしいですか？' }
    - else
      .board-author
        %p 管理者
        .board-image
          = image_tag @board.user.avatar_image
        .board-name= @board.user.display_name
  .filter
    = search_form_for @q, url: board_path(@board), method: :get, html: { class: 'search-form' } do |f|
      .search-item
        .search-sorts
          %p= sort_link(@q, :id, "カード番号", class: 'filter-button')
          %p= sort_link(@q, :deadline, "締切", class: 'filter-button')
      .search-item
        = f.search_field :title_cont, placeholder: "タイトルを入力", class: 'filter-box'
        .search-buttons
          = f.submit "検索", class: 'filter-button'
          = link_to "リセット", board_path(@board), class: 'filter-button'
  :javascript
    document.addEventListener("turbo:load", function () {
      // クエリ削除（初回ロード時のみ）
      if (window.location.search.length > 0) {
        const url = new URL(window.location.href);
        url.search = "";
        history.replaceState(null, "", url);
      }
    });
    // ブラウザバック検出してリロード
    window.addEventListener("pageshow", function (event) {
      const navType = performance.getEntriesByType("navigation")[0]?.type;
      if (event.persisted || navType === "back_forward") {
        location.reload();
      }
    });


  .cards
    - @cards.each do |card|
      .cards-item
        = link_to board_card_path(@board, card), class: 'cards-link', data: { turbo: false } do
          .cards-content-top
            .cards-title
              %span= "C%03d:" % card.id
              = card.title
          .cards-content-middle
            .cards-status
              %p= image_tag 'status.svg'
              %p= t("enums.card.status.#{card.status}")
            .cards-deadline
              %p= image_tag 'deadline.svg'
              %p= card.deadline
          .cards-description= card.description
          .cards-content-bottom
            .cards-author
              %p 担当者
              .cards-image
                = image_tag card.user.avatar_image
              .cards-name= card.user.display_name
            .cards-comment
              .cards-comment-number= card.comment_count
              .cards-comment-icon
                = image_tag 'comment.svg'
  .pagination-wrapper
    = paginate @cards, params: request.query_parameters, theme: nil

  - if user_signed_in?
    = link_to new_board_card_path(@board), class: 'create' do
      .create-content ＋ 新しいカードを追加