config/routes.rb
Rails.application.routes.draw do
  # 認証ページURLパスを変更
  devise_for :users, path_names: {
  sign_in: "login",
  sign_out: "logout",
  sign_up: "register"
  }

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: "boards#index"
  resources :boards do
    resources :cards do
      resources :comments, only: [ :new, :create ]
    end
  end

  resource :profiles, only: [ :show, :edit, :update ]

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/card.rb
# == Schema Information
#
# Table name: cards
#
#  id          :bigint           not null, primary key
#  deadline    :date
#  description :text             not null
#  status      :integer          default(0), not null
#  title       :string           not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  board_id    :bigint           not null
#  user_id     :bigint           not null
#
# Indexes
#
#  index_cards_on_board_id  (board_id)
#  index_cards_on_user_id   (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (board_id => boards.id)
#  fk_rails_...  (user_id => users.id)
#
class Card < ApplicationRecord
  validates :title,
    presence: true,
    length: { minimum: 2, maximum: 100 },
    format: { with: /\A(?!\@)/ }
  validates :description,
    presence: true,
    length: { minimum: 5 }
  validate :deadline_cannot_be_in_the_past
  belongs_to :user
  belongs_to :board
  has_one_attached :eyecatch
  has_many :comments, dependent: :destroy
  has_one :profile, through: :user
  enum :status, { waiting: 0, progress: 1, close: 2 }
  def comment_count
    comments.count
  end
  def self.ransackable_attributes(auth_object = nil)
    %w[id title deadline created_at updated_at]
  end
  def self.ransackable_associations(auth_object = nil)
    %w[user profile]
  end
  private
  def deadline_cannot_be_in_the_past
    return if deadline.blank?
    if deadline < Date.today
      errors.add(:deadline, :in_future)
    end
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :authenticate_user!, only: [ :new, :create, :edit, :update, :destroy ]




def show
  @board = Board.find(params[:board_id])
  @card = @board.cards.find(params[:id])
  @q = @card.comments.includes(:user).ransack(params[:q])
  @q.sorts = [ "created_at desc" ] if @q.sorts.empty?
  @comments = @q.result
end

  def new
    @board = Board.find(params[:board_id])  # URLのboard_idから対象のboardを取得
    @card = @board.cards.build  # boardに紐づけてカードを作成
  end

  def create
    @board = Board.find(params[:board_id])  # URLのboard_idから対象のboardを取得
    @card = @board.cards.build(card_params) # 取得したBoardに紐づく新しいCardを作成
    @card.user = current_user # カードの投稿者に現在ログインしているユーザーを設定
    if @card.save
      redirect_to board_card_path(@board, @card), notice: "保存できました" # 保存後、ネストされたカードの詳細ページ /boards/:board_id/cards/:id にリダイレクト
    else
      render :new, status: :unprocessable_entity
    end
  end


  def edit
    @card = Card.find(params[:id])
    @board = @card.board
  end

  def update
    @card = Card.find(params[:id])
    @board = @card.board
    if @card.update(card_params)
      redirect_to board_card_path(@board, @card), notice: "更新できました"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @board = Board.find(params[:board_id]) # board を特定
    @card = @board.cards.find(params[:id]) # board に紐づく card を取得
    @card.destroy!
    redirect_to board_cards_path(@board), status: :see_other, notice: "削除に成功しました"
  end

  private

  def card_params
    params.require(:card).permit(:title, :description, :deadline, :status, :eyecatch)
  end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/_form.html.haml
.form
  - if card.errors.any?
    .alert.alert-danger
      %ul
        - card.errors.full_messages.each do |message|
          %li= message

  = form_with(model: [@board, @card], local: true) do |f|
    .form-field
      = f.label :title, class: 'form-label'
      = f.text_field :title, class: 'form-text'

    .form-field
      = f.label :description, class: 'form-label'
      = f.text_area :description, class: 'form-text text-area'

    .form-field
      = f.label :status, class: 'form-label'
      = f.select :status,Card.statuses.keys.map { |key| [t("enums.card.status.#{key}"), key] }, {}, class: 'form-text'

    .form-field
      = f.label :deadline, class: 'form-label'
      = f.date_field :deadline, class: 'form-text'

    .form-actions
      = f.submit '保存', class: 'btn-primary'

app/views/cards/edit.html.haml
.inner.inner-form
  %h2 カードの編集

  - if @card.eyecatch.attached?
    .eyecatch-preview
      = image_tag @card.eyecatch, alt: '登録済みのアイキャッチ', class: 'eyecatch-image'

  = render 'form', board: @board, card: @card

app/views/cards/index.html.haml
.inner
  .card-top
    .card-title
      %h2= @board.title
      %h3= @board.description
    - if user_signed_in? && current_user.boards.exists?(id: @board.id)
      .card-actions
        .card-icon
          = image_tag 'actions.svg', alt: 'Actions Icon'
          .dropdown-content.mini
            = link_to '編集する', edit_board_path(@board)
            = link_to '削除する', board_path(@board), data: { turbo_method: 'delete', turbo_confirm: '本当に削除してもよろしいですか？' }
    - else
      .board-author
        %p 管理者
        .board-image
          = image_tag @board.user.avatar_image
        .board-name= @board.user.display_name
    - next_direction = params[:direction] == 'asc' ? 'desc' : 'asc'
  .filter
    = form_with url: board_cards_path(@board), method: :get, local: true, class: 'search-form' do
      .search-form
        = select_tag :sort,options_for_select([['タイトル', 'title'],['ステータス', 'status'],['締切', 'deadline'],['担当者', 'nickname']], params[:sort]),class: 'filter-box'
        - current_direction = params[:direction] || 'asc'
        - next_direction = params[:direction] == 'asc' ? 'desc' : 'asc'
        = hidden_field_tag :direction, next_direction
        = hidden_field_tag :q, params[:q]   # ← これが重要！
        - button_label = current_direction == 'asc' ? '並び替え ↓' : '並び替え ↑'
        = submit_tag button_label, class: 'filter-button'

    = form_with url: board_cards_path(@board), method: :get, local: true, class: 'search-form' do
      = text_field_tag :q, params[:q], placeholder: "タイトルを入力", class: 'filter-box'
      .search-buttons
        = submit_tag "検索", class: 'filter-button'
        = link_to "リセット", board_cards_path(@board), class: 'filter-button'
  .cards
    - @cards.each do |card|
      .cards-item
        = link_to board_card_path(@board, card), class: 'cards-link' do
          .cards-content-top
            .cards-title= card.title
          .cards-content-middle
            .cards-status
              %p= image_tag 'status.svg'
              %p= t("enums.card.status.#{card.status}")
            .cards-deadline
              %p= image_tag 'deadline.svg'
              %p= card.deadline
          .cards-description= card.description
          .cards-content-bottom
            .cards-author
              %p 担当者
              .cards-image
                = image_tag card.user.avatar_image
              .cards-name= card.user.display_name
            .cards-comment
              .cards-comment-number= card.comment_count
              .cards-comment-icon
                = image_tag 'comment.svg'

  - if user_signed_in?
    = link_to new_board_card_path(@board), class: 'create' do
      .create-content ＋ 新しいカードを追加

app/views/cards/new.html.haml
.inner.inner-form
  %h2 新しいカードを作成
  = render 'form', board: @board, card: @card # 部分テンプレート _form.html.haml に board と card を変数として渡す

app/views/cards/show.html.haml
.inner.is-card
  .board-back= link_to "＜ #{"B%03d:" % @board.id}#{ @board.title} に戻る", board_path(@board)
  .card
    .card-top
      .card-title
        %h2
          %span= "C%03d:" % @card.id
          = @card.title
      - if user_signed_in? && current_user == @card.user
        .card-actions
          .card-icon
            = image_tag 'actions.svg', alt: 'Actions Icon'
            .dropdown-content.mini
              = link_to '編集する', edit_board_card_path(@card)
              = link_to '削除する', board_card_path(@board, @card), data: { turbo_method: 'delete', turbo_confirm: '本当に削除してもよろしいですか？' }
    .card-status
      .card-progress
        %p= image_tag 'status.svg'
        %p= t("enums.card.status.#{@card.status}")
      .card-deadline
        %p= image_tag 'deadline.svg'
        %p= @card.deadline
    .card-text
      .card-description
        = @card.description
        .card-comment-date= l(@card.created_at, format: :long)
      .card-author
        %p= '担当者'
        .card-image
          = image_tag @card.user.avatar_image
        .card-name= @card.user.display_name

    .card-comment
      .card-comment-title
        %p= t('activerecord.attributes.card.comment_title')
        = sort_link @q, :created_at, '投稿日時', default_order: :desc, class:'filter-button'
      - @comments.each do |comment|
        - owner_comment = (comment.user_id == @card.user_id)
        .card-comment-content{ class: ("is-owner" if owner_comment) }
          .card-author
            .card-image
              = image_tag comment.user.avatar_image
            .card-name= comment.user.display_name
          .card-comment-text
            %p= comment.content
            .card-comment-date= l(comment.created_at, format: :long)
    :javascript
      document.addEventListener("turbo:load", function () {
        // クエリ削除（初回ロード時のみ）
        if (window.location.search.length > 0) {
          const url = new URL(window.location.href);
          url.search = "";
          history.replaceState(null, "", url);
        }
      });
      // ブラウザバック検出してリロード
      window.addEventListener("pageshow", function (event) {
        const navType = performance.getEntriesByType("navigation")[0]?.type;
        if (event.persisted || navType === "back_forward") {
          location.reload();
        }
      });
  - if user_signed_in?
    = link_to new_board_card_comment_path(@board, @card), class: 'create', data: { turbo: false } do
      .create-content ＋ 新しいコメントを追加